### ISSUE TITLE
sdb crashes when shell pipeline fails

### ISSUE THREAD

**Issue by sdimitro** [delphix/sdb#14]
```
> addr init_task ! task_struct
/bin/sh: 1: task_struct: not found
Traceback (most recent call last):
  File "/usr/local/bin/sdb", line 11, in <module>
    load_entry_point('sdb==0.1.0', 'console_scripts', 'sdb')()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/cli.py", line 216, in main
    repl.start_session()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 114, in start_session
    _ = self.eval_cmd(line)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 88, in eval_cmd
    print(obj)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by sdimitro** [comment]
The above may be related to #9

**Comment by ahrens** [comment]
The behavior is slightly different now.  sdb doesn't exit, but it does print an unfriendly message:
```
sdb> addr init_task ! task_struct
/bin/sh: 1: task_struct: not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 90, in eval_cmd
    print(obj)
BrokenPipeError: [Errno 32] Broken pipe
sdb>
```
