### ISSUE TITLE
ptype crash

### ISSUE THREAD

**Issue by sdimitro** [delphix/sdb#172]
```
sdb> ptype struct znode
sdb encountered an internal error due to a bug. Here's the
information you need to file the bug:
----------------------------------------------------------
Target Info:
	ProgramFlags.IS_LIVE|IS_LINUX_KERNEL
	Platform(<Architecture.X86_64: 1>, <PlatformFlags.IS_LITTLE_ENDIAN|IS_64_BIT: 3>)

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 85, in eval_cmd
    for obj in invoke(self.target, [], input_):
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/pipeline.py", line 165, in invoke
    yield from execute_pipeline(first_input, pipeline)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/pipeline.py", line 83, in execute_pipeline
    yield from massage_input_and_call(pipeline[-1], this_input)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/pipeline.py", line 43, in massage_input_and_call
    yield from cmd.call(objs)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/command.py", line 279, in call
    result = self._call(objs)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/commands/ptype.py", line 109, in _call
    print(sdb.get_prog().type(f"{prefix}{tp_name}"))
  File "<string>", line None
SyntaxError: expected identifier after 'struct'
----------------------------------------------------------
Link: https://github.com/delphix/sdb/issues/new
```

**Comment by sdimitro** [comment]
this same crash should happen for `enum` and `union` too.

**Comment by sdimitro** [comment]
No longer an issue:
```
sdb>  ptype struct znode
sdb: ptype: skip keyword 'struct' or quote your type "struct <typename>"
```

**Comment by sdimitro** [comment]
For the record the correct usage is one of the following 2:
```
sdb>  ptype znode
struct znode {
	uint64_t z_id;
	kmutex_t z_lock;
	krwlock_t z_parent_lock;
	krwlock_t z_name_lock;
...
}
sdb>  ptype "struct znode"
struct znode {
	uint64_t z_id;
	kmutex_t z_lock;
	krwlock_t z_parent_
```
