### ISSUE TITLE
page not present error when reading kdump with `drgn`

### ISSUE THREAD

**Issue by sdimitro** [delphix/sdb#18]
George (@grwilson)  hit the following error while running `stacks` on a crash dump:
```
`> stacks
TASK_STRUCT        STATE             COUNT
==========================================
Traceback (most recent call last):
  File "/usr/local/bin/sdb", line 11, in <module>
    load_entry_point('sdb==0.1.0', 'console_scripts', 'sdb')()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/cli.py", line 216, in main
    repl.start_session()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 114, in start_session
    _ = self.eval_cmd(line)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 87, in eval_cmd
    for obj in objs:
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/__init__.py", line 180, in invoke
    yield from execute_pipeline(prog, first_input, pipeline)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/__init__.py", line 77, in execute_pipeline
    yield from pipeline[-1].call(this_input)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/commands/stacks.py", line 226, in call
    for frame in self.prog.stack_trace(task):
_drgn.FaultError: kdump_read: Cannot get page I/O address: Page not present: pte[479] = 0x0
```

I haven't had the time to look at the actual failure myself as that system is unavailable for me right now. Besides getting our hadns in that core dump and see exactly what page was missing it would be interesting to see if `drgn` itself dumped core.

Note though that this is a `drgn` issue and probably won't be fixed within `sdb`. We just file it here for now until we get more concrete information.

**Comment by grwilson** [comment]
The following crash dump exhibits this problem: http://scale-datastore.delphix.com/storage/scale-dlpx-6.0.0.0-200K-1.scale-dc/cores/201911112019/
