### ISSUE TITLE
sessions crashed looking at crash dump due to `FaultError` when trying to find memory segment

### ISSUE THREAD

**Issue by sdimitro** [delphix/sdb#23]
```
> echo 0xffff94af8f422840 | cast struct rq * | member curr
Traceback (most recent call last):
  File "/usr/bin/sdb", line 11, in <module>
    load_entry_point('sdb==0.1.0', 'console_scripts', 'sdb')()
  File "/usr/lib/python3/dist-packages/sdb/internal/cli.py", line 216, in main
    repl.start_session()
  File "/usr/lib/python3/dist-packages/sdb/internal/repl.py", line 114, in start_session
    _ = self.eval_cmd(line)
  File "/usr/lib/python3/dist-packages/sdb/internal/repl.py", line 88, in eval_cmd
    print(obj)
_drgn.FaultError: could not find memory segment containing 0xffff94af8f4231b0
```

This is obviously a `drgn` problem but still the session shouldn't be crashing. The fix may be similar to whatever we end up doing for https://github.com/delphix/sdb/issues/19

**Comment by sdimitro** [comment]
I was wrong, that was on a live system which makes it the same as #19
