### ISSUE TITLE
complaints about prog.pointer_type call

### ISSUE THREAD

**Issue by PaulZ-98** [delphix/sdb#252]
** Expected Behavior**
Issued "dbuf" command, expected list of dbufs.

** Actual Behavior**
sdb> dbuf
                addr   object  lvl    blkid holds os
dmu_buf_impl_t *
struct dmu_buf_impl *
sdb encountered an internal error due to a bug. Here's the
information you need to file the bug:
----------------------------------------------------------
Target Info:
	ProgramFlags.IS_LIVE|IS_LINUX_KERNEL
	Platform(<Architecture.X86_64: 1>, <PlatformFlags.IS_LITTLE_ENDIAN|IS_64_BIT: 3>)

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/internal/repl.py", line 107, in eval_cmd
    for obj in invoke(self.target, [], input_):
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/pipeline.py", line 146, in invoke
    yield from execute_pipeline(first_input, pipeline)
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/pipeline.py", line 83, in execute_pipeline
    yield from massage_input_and_call(pipeline[-1], this_input)
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/pipeline.py", line 66, in massage_input_and_call
    yield from cmd.call(objs)
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/command.py", line 328, in call
    yield from self.__invalid_memory_objects_check(
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/command.py", line 290, in __invalid_memory_objects_check
    for obj in objs:
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/command.py", line 775, in _call
    self.pretty_print(self.caller(objs))
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/commands/zfs/dbuf.py", line 87, in pretty_print
    for dbuf in filter(self.argfilter, dbufs):
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/command.py", line 731, in caller
    baked[type_canonicalize_name(
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/target.py", line 132, in type_canonicalize_name
    return type_canonical_name(prog.type(type_name))
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/target.py", line 124, in type_canonical_name
    return str(type_canonicalize(t).type_name())
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/target.py", line 113, in type_canonicalize
    return prog.pointer_type(type_canonicalize(t.type), t.size)
TypeError: expected Qualifiers or None, not int
----------------------------------------------------------
Link: https://github.com/delphix/sdb/issues/new
sdb> 

**Steps To Reproduce the Problem**
Ubuntu 20.04
installed drgn and sdb per the instructions
sdb> dbuf

**Comment by PaulZ-98** [comment]
This seemed to fix it.
{code}
root@ub-20:~/sdb# git diff
diff --git a/sdb/target.py b/sdb/target.py
index b20cc13..1773980 100644
--- a/sdb/target.py
+++ b/sdb/target.py
@@ -108,7 +108,7 @@ def type_canonicalize(t: drgn.Type) -> drgn.Type:
     if t.kind == drgn.TypeKind.TYPEDEF:
         return type_canonicalize(t.type)
     if t.kind == drgn.TypeKind.POINTER:
-        return prog.pointer_type(type_canonicalize(t.type), t.size)
+        return prog.pointer_type(type_canonicalize(t.type), None)
     if t.kind == drgn.TypeKind.ARRAY:
         return prog.array_type(type_canonicalize(t.type), t.length)
     return t.unqualified()
{\code}

**Comment by PaulZ-98** [comment]
```
sdb> dbuf
                addr   object  lvl    blkid holds os
  0xffff88d119070200       15    0        0     0 tank/_MOS
  0xffff88d118cbc200        4    0        0     0 tank/_MOS
  0xffff88d11d3ff000       71    0        0     0 tank/_MOS
  0xffff88d118cb9e00       36    0        0     0 tank
  0xffff88d11d661000        0    0        0    21 tank/_MOS
...
...
```

**Comment by sdimitro** [comment]
Hey @PaulZ-98,

Thanks for filling the bug! The error displayed to you and your fix seem a bit weird to me.
Our nightly tests for `sdb` have been passing for a while with no problem. I also just tried the latest bits on one of my servers and it seems to work fine.

Looking at `drgn`'s API online (here: https://drgn.readthedocs.io/en/latest/api_reference.html#drgn.Program.pointer_type) - I see that t.size should indeed be the second parameter and its type should be int:
```
Program.pointer_type(type, size=None, *, qualifiers=Qualifiers.NONE, language=None)
...

Parameters:
...
    type (Type) – The referenced type (Type.type)
    size (Optional[int]) – Type.size, or None to use the program’s default pointer size.
...
```
So the current code without your patch should be fine.

Looking at your output copy pasted above, it seems like in your case an int (`t.size`) is passed as the `qualifiers` parameter which expects a Qualifier Type. This seems bizarre to me as `size` should be the second argument. Can you print your exact `drgn` (I know you said latest but verifying this would be nice) and Python version (I know it says 3.8 on the output)? I want to setup everything as you have it. It really seems to me that for some reason an older version of `drgn` was installed.

P.S. Did you use `pip` to install it? Can you try cloning the repo and manually running `sudo python3 setup.py install` from the root of the repo?

**Comment by PaulZ-98** [comment]
drgn version is 0.0.7 - I installed it with pip.  Let me try building it as you suggested.
```
root@ub-20:~/sdb# drgn
could not get debugging information for:
/usr/lib/modules/5.4.0-52-generic/misc/vboxguest.ko (libdwfl error: No DWARF information found)
/usr/lib/modules/5.4.0-52-generic/misc/vboxvideo.ko (libdwfl error: No DWARF information found)
drgn 0.0.7 (using Python 3.8.5, without libkdumpfile)
For help, type help(drgn).
>>> import drgn
>>> from drgn import NULL, Object, cast, container_of, execscript, reinterpret, sizeof
>>> from drgn.helpers.linux import *
>>> 
```
