### ISSUE TITLE
Attempting to run sdb [userland binary] [core] segfaulted

### ISSUE THREAD

**Issue by rincebrain** [delphix/sdb#282]
** Expected Behavior**
I'd have liked an interactive debugging session.

** Actual Behavior**
(Note that "core" was overwritten by the core dump, so I'm not trying to run sdb against an sdb core dump and an unrelated binary...)
```
$ sdb cmd/ztest/.libs/ztest core
Segmentation fault (core dumped)
$ gdb /usr/bin/python3 core
[...]
(gdb) bt
#0  read_addrs (n=4, addrs=<synthetic pointer>, read_vaddr=<synthetic pointer>, vaddr=<optimized out>, buffer_available=0x7ffdf7572b20, buffer=0x7ffdf7572b18, elfdata=1 '\001', elfclass=2 '\002', closure=<synthetic pointer>)
    at link_map.c:286
#1  report_r_debug (memory_callback=0x7f82acd7c230 <integrated_memory_callback>, r_debug_info=0x7ffdf7572c78, memory_callback_arg=0x7ffdf7572b70, r_debug_vaddr=<optimized out>, dwfl=0x236e1b0, elfdata=1 '\001', elfclass=2 '\002')
    at link_map.c:341
#2  dwfl_link_map_report (dwfl=dwfl@entry=0x236e1b0, auxv=auxv@entry=0x2370c38, auxv_size=auxv_size@entry=320, memory_callback=memory_callback@entry=0x7f82acd7df50 <dwfl_elf_phdr_memory_callback>,
    memory_callback_arg=memory_callback_arg@entry=0x234db50, r_debug_info=r_debug_info@entry=0x7ffdf7572c78) at link_map.c:1054
#3  0x00007f82acd7ed6c in dwfl_core_file_report (dwfl=0x236e1b0, elf=0x234db50, executable=executable@entry=0x0) at core-file.c:547
#4  0x00007f82acde144b in userspace_report_debug_info (load=<optimized out>) at ../../libdrgn/debug_info.c:645
#5  drgn_debug_info_load (dbinfo=0x227e890, paths=paths@entry=0x0, n=n@entry=0, load_default=load_default@entry=true, load_main=load_main@entry=true) at ../../libdrgn/debug_info.c:1118
#6  0x00007f82ace0827e in drgn_program_load_debug_info (prog=0x234d820, paths=paths@entry=0x0, n=n@entry=0, load_default=load_default@entry=true, load_main=load_main@entry=true) at ../../libdrgn/program.c:617
#7  0x00007f82acdd360c in Program_load_default_debug_info (self=<optimized out>) at ../../libdrgn/python/program.c:518
#8  0x00000000005313a9 in ?? ()
#9  0x0000000000512192 in _PyEval_EvalFrameDefault ()
#10 0x0000000000528b63 in _PyFunction_Vectorcall ()
#11 0x0000000000511fb5 in _PyEval_EvalFrameDefault ()
#12 0x0000000000528b63 in _PyFunction_Vectorcall ()
#13 0x0000000000511fb5 in _PyEval_EvalFrameDefault ()
#14 0x00000000005106ed in ?? ()
#15 0x0000000000510497 in _PyEval_EvalCodeWithName ()
#16 0x00000000005f5be3 in PyEval_EvalCode ()
#17 0x0000000000619de7 in ?? ()
#18 0x0000000000615610 in ?? ()
#19 0x0000000000619d79 in ?? ()
#20 0x0000000000619816 in PyRun_SimpleFileExFlags ()
#21 0x000000000060d4e3 in Py_RunMain ()
#22 0x00000000005ea6e9 in Py_BytesMain ()
#23 0x00007f82ad5b4d0a in __libc_start_main (main=0x5ea6b0, argc=4, argv=0x7ffdf75737d8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdf75737c8) at ../csu/libc-start.c:308
#24 0x00000000005ea5ea in _start ()
```

**Steps To Reproduce the Problem**
As above. (I'm reasonably confident I'm not asking something unreasonable of it, since s/sdb/gdb/ opens a debugger prompt, gdb's tooling is just much less nice...)

**Version**
Debian bullseye amd64 up to date as of 20211122, sdb and drgn up to date git clones as of same (drgn v0.0.14-71-gd18be05, sdb 3e6c69ab6ab498204aa4a66ea985a61ea1d2f12a)

**Additional Context**
I've backed up the build artifacts that result in this, but the tarball is pretty large, so just ask if you'd like it.

**Comment by rincebrain** [comment]
Seems to be osandov/drgn#130, not an sdb problem (or, technically, a drgn problem...)
