### ISSUE TITLE
[Feb 01, 2022] [BUG] AttributeError: 'struct kmem_cache' has no member 'memcg_params'

### ISSUE THREAD

**Issue by Balamuruhan** [delphix/sdb#284]
** Expected Behavior**
Environment refresh with Python 3.8 based dvp should work

** Actual Behavior**
Environment refresh after uploading Python 3.8 dvp based plugin fails with internal error and `spl_kmem_caches_600.log` in stat directory has following traceback.

```
----------------------------------------------------------
Target Info:
ProgramFlags.IS_LIVE|IS_LINUX_KERNEL
Platform(<Architecture.X86_64: 1>, <PlatformFlags.IS_LITTLE_ENDIAN|IS_64_BIT: 3>)

----------------------------------------------------------
Link: https://github.com/delphix/sdb/issues/new
----- 2022-01-31 13:03:09.558283424 -----
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/sdb/internal/repl.py", line 107, in eval_cmd
for obj in invoke(self.target, [], input_):
File "/usr/lib/python3/dist-packages/sdb/pipeline.py", line 153, in invoke
yield from execute_pipeline(first_input, pipeline)
File "/usr/lib/python3/dist-packages/sdb/pipeline.py", line 84, in execute_pipeline
yield from massage_input_and_call(pipeline[-1], this_input)
File "/usr/lib/python3/dist-packages/sdb/pipeline.py", line 67, in massage_input_and_call
yield from cmd.call(objs)
File "/usr/lib/python3/dist-packages/sdb/command.py", line 328, in call
yield from self.__invalid_memory_objects_check(
File "/usr/lib/python3/dist-packages/sdb/command.py", line 290, in __invalid_memory_objects_check
for obj in objs:
File "/usr/lib/python3/dist-packages/sdb/command.py", line 775, in _call
self.pretty_print(self.caller(objs))
File "/usr/lib/python3/dist-packages/sdb/commands/spl/spl_kmem_caches.py", line 193, in pretty_print
row_dict = {
File "/usr/lib/python3/dist-packages/sdb/commands/spl/spl_kmem_caches.py", line 194, in <dictcomp>
field: SplKmemCaches.FIELDS[field](obj) for field in fields
File "/usr/lib/python3/dist-packages/sdb/commands/spl/internal/kmem_helpers.py", line 145, in total_memory
return slub.total_memory(cache.skc_linux_cache)
File "/usr/lib/python3/dist-packages/sdb/commands/linux/internal/slub_helpers.py", line 82, in total_memory
nslabs = nr_slabs(cache)
File "/usr/lib/python3/dist-packages/sdb/commands/linux/internal/slub_helpers.py", line 59, in nr_slabs
if is_root_cache(cache):
File "/usr/lib/python3/dist-packages/sdb/commands/linux/internal/slub_helpers.py", line 30, in is_root_cache
return int(cache.memcg_params.root_cache.value_()) == 0x0
AttributeError: 'struct kmem_cache' has no member 'memcg_params'
sdb encountered an internal error due to a bug. Here's the
information you need to file the bug:
----------------------------------------------------------
Target Info:
ProgramFlags.IS_LIVE|IS_LINUX_KERNEL
Platform(<Architecture.X86_64: 1>, <PlatformFlags.IS_LITTLE_ENDIAN|IS_64_BIT: 3>)

----------------------------------------------------------
Link: https://github.com/delphix/sdb/issues/new
```

**Steps To Reproduce the Problem**
1. Add host environment to Engine
2. Install dvp == 4.0.2, build EBS 12.2 vsdk based plugin and upload it to the Engine.
3. Perform Environment refresh

**Screenshots**
Attached screenshots with this issue

**Version**
Engine:
Product Dynamic Data Platform
Version Dynamic Data Platform 6.1.0.0
Build Date Jan 29, 2022 9:07:14 AM

dvp version: 4.0.2
Python 3.8.10

**Additional Context**
Attached debug logs for reference

**Comment by sdimitro** [comment]
Fixed in https://github.com/delphix/sdb/pull/334
