### ISSUE TITLE
Walk command is broken

### ISSUE THREAD

**Issue by sdimitro** [delphix/sdb#296]
```
sdb> walk
sdb encountered an internal error due to a bug. Here's the
information you need to file the bug:
----------------------------------------------------------
Target Info:
	ProgramFlags.IS_LINUX_KERNEL
	Platform(<Architecture.X86_64: 1>, <PlatformFlags.IS_LITTLE_ENDIAN|IS_64_BIT: 3>)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdb/internal/repl.py", line 107, in eval_cmd
    for obj in invoke(self.target, [], input_):
  File "/usr/lib/python3/dist-packages/sdb/pipeline.py", line 153, in invoke
    yield from execute_pipeline(first_input, pipeline)
  File "/usr/lib/python3/dist-packages/sdb/pipeline.py", line 84, in execute_pipeline
    yield from massage_input_and_call(pipeline[-1], this_input)
  File "/usr/lib/python3/dist-packages/sdb/pipeline.py", line 43, in massage_input_and_call
    yield from cmd.call(objs)
  File "/usr/lib/python3/dist-packages/sdb/command.py", line 325, in call
    yield from self.__invalid_memory_objects_check(
  File "/usr/lib/python3/dist-packages/sdb/command.py", line 287, in __invalid_memory_objects_check
    for obj in objs:
  File "/usr/lib/python3/dist-packages/sdb/command.py", line 613, in _call
    print(Walk._help_message())
  File "/usr/lib/python3/dist-packages/sdb/command.py", line 590, in _help_message
    msg += f"\t{'WALKER':-20s} {'TYPE':-20s}\n"
ValueError: Sign not allowed in string format specifier
----------------------------------------------------------
Link: https://github.com/delphix/sdb/issues/new
```

**Comment by sdimitro** [comment]
Fixed in 6.0/stage. Should propagate to master soon
