### ISSUE TITLE
crash when using "cast" command: SyntaxError: invalid character \x27

### ISSUE THREAD

**Issue by prakashsurya** [delphix/sdb#39]
```
> addr 0xffff88d07f003080 | cast struct kmem_cache *'
Traceback (most recent call last):
  File "/usr/local/bin/sdb", line 11, in <module>
    load_entry_point('sdb==0.1.0', 'console_scripts', 'sdb')()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/cli.py", line 216, in main
    repl.start_session()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 114, in start_session
    _ = self.eval_cmd(line)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 87, in eval_cmd
    for obj in objs:
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/__init__.py", line 154, in invoke
    pipeline.append(all_commands[name](prog, args, name))
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/commands/cast.py", line 39, in __init__
    self.type = self.prog.type(tname)
SyntaxError: invalid character \x27
```

**Comment by sdimitro** [comment]
With the new parser introduced here -> https://github.com/delphix/sdb/pull/219

this is no longer an issue and we get a nice error message instead:
```
sdb> addr 0xffff88d07f003080 | cast struct kmem_cache *'
sdb: syntax error: unfinished string expression
  addr 0xffff88d07f003080 | cast struct kmem_cache *'
                                                    ^
```
