### ISSUE TITLE
sdb requires sudo just for the history file to be accessed

### ISSUE THREAD

**Issue by sdimitro** [delphix/sdb#56]
```
[256] sdb ./cmd/ztest/.libs/ztest ./core
Traceback (most recent call last):
  File "/usr/local/bin/sdb", line 11, in <module>
    load_entry_point('sdb==0.1.0', 'console_scripts', 'sdb')()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/cli.py", line 206, in main
    prog = setup_target(args)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/cli.py", line 162, in setup_target
    args.symbol_search.insert(0, args.object)
AttributeError: 'NoneType' object has no attribute 'insert'
[257] sdb ./cmd/ztest/.libs/ztest ./core -s ./cmd/ztest/.libs/ztest
Traceback (most recent call last):
  File "/usr/local/bin/sdb", line 11, in <module>
    load_entry_point('sdb==0.1.0', 'console_scripts', 'sdb')()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/cli.py", line 211, in main
    repl = REPL(prog, sdb.all_commands)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 62, in __init__
    readline.read_history_file(histfile)
PermissionError: [Errno 13] Permission denied
```

**Comment by sdimitro** [comment]
Recently we were looking at a ZFS bug and drgn/sdb would hang because they'd create the history file on top of ZFS and hang as a result. To avoid this situation in the future potentially while also dealing with the above issue we may want to have env var to specify the history file (we could redirect that to /dev/null or somewhere not on zfs  for this issue, and its default can be something user specific so its permissions would not get intermingled when sudo is used).
