### ISSUE TITLE
TypeError: command "['metaslab']" requires an input

### ISSUE THREAD

**Issue by prakashsurya** [delphix/sdb#64]
```
> metaslab
Traceback (most recent call last):
  File "/usr/local/bin/sdb", line 11, in <module>
    load_entry_point('sdb==0.1.0', 'console_scripts', 'sdb')()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/cli.py", line 216, in main
    repl.start_session()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 114, in start_session
    _ = self.eval_cmd(line)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 87, in eval_cmd
    for obj in objs:
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/__init__.py", line 180, in invoke
    yield from execute_pipeline(prog, first_input, pipeline)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/__init__.py", line 77, in execute_pipeline
    yield from pipeline[-1].call(this_input)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/locator.py", line 119, in call
    self.pretty_print(self.caller(objs))
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/commands/zfs/metaslab.py", line 159, in pretty_print
    for msp in metaslabs:
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/locator.py", line 111, in caller
    yield from self.no_input()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/locator.py", line 51, in no_input
    raise TypeError('command "{}" requires an input'.format(self.names))
TypeError: command "['metaslab']" requires an input
```

**Comment by ahrens** [comment]
I think that what's being printed here is accurate: `command "['metaslab']" requires an input`.  Is the bug that we should format it nicer? (Also, I imagine #74 is particularly annoying here.)
