### ISSUE TITLE
TypeError: command "['metaslab']" does not handle input of type spa_t *

### ISSUE THREAD

**Issue by prakashsurya** [delphix/sdb#65]
```
> spa | metaslab
The following types have walkers:
        WALKER               TYPE
        ['avl']              avl_tree_t *
        ['spl_list']         list_t *
Traceback (most recent call last):
  File "/usr/local/bin/sdb", line 11, in <module>
    load_entry_point('sdb==0.1.0', 'console_scripts', 'sdb')()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/cli.py", line 216, in main
    repl.start_session()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 114, in start_session
    _ = self.eval_cmd(line)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 87, in eval_cmd
    for obj in objs:
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/__init__.py", line 180, in invoke
    yield from execute_pipeline(prog, first_input, pipeline)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/__init__.py", line 77, in execute_pipeline
    yield from pipeline[-1].call(this_input)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/locator.py", line 119, in call
    self.pretty_print(self.caller(objs))
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/commands/zfs/metaslab.py", line 159, in pretty_print
    for msp in metaslabs:
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/locator.py", line 109, in caller
    self.names, i.type_))
TypeError: command "['metaslab']" does not handle input of type spa_t *
```

**Comment by ahrens** [comment]
I think that what's being printed here is accurate: `command "['metaslab']" does not handle input of type spa_t *`. Is the bug that we should format it nicer? (Also, I imagine #74 is particularly annoying here.)

**Comment by prakashsurya** [comment]
I think the fix would be to catch the `TypeError`, and convert that into something (i.e. an `sdb.error` exception) that SDB expects and can properly handle.

And yea.. this probably also depends on how we decide to resolve #74.

**Comment by prakashsurya** [comment]
So based on the discussions we've had w.r.t. #74, should this still be considered a bug?

**Comment by ahrens** [comment]
Yes, because #74 is about handling bugs.  It isn't a bug to run `spa | metaslab`
