### ISSUE TITLE
AttributeError: 'zfs_btree_t' has no member 'avl_numnodes'

### ISSUE THREAD

**Issue by prakashsurya** [delphix/sdb#66]
```
> spa rpool | vdev | metaslab
 ADDR                 ID           OFFSET     FREE  FRAG     UCMU
 -----------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/sdb", line 11, in <module>
    load_entry_point('sdb==0.1.0', 'console_scripts', 'sdb')()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/cli.py", line 216, in main
    repl.start_session()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 114, in start_session
    _ = self.eval_cmd(line)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 87, in eval_cmd
    for obj in objs:
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/__init__.py", line 180, in invoke
    yield from execute_pipeline(prog, first_input, pipeline)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/__init__.py", line 77, in execute_pipeline
    yield from pipeline[-1].call(this_input)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/locator.py", line 119, in call
    self.pretty_print(self.caller(objs))
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/commands/zfs/metaslab.py", line 161, in pretty_print
    Metaslab.print_metaslab(self.prog, msp, first_time, indent)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/commands/zfs/metaslab.py", line 137, in print_metaslab
    uchanges_free_mem = msp.ms_unflushed_frees.rt_root.avl_numnodes
AttributeError: 'zfs_btree_t' has no member 'avl_numnodes'
```

**Comment by prakashsurya** [comment]
cc: @grwilson @pcd1193182

**Comment by sdimitro** [comment]
cc @shartse has some preliminary implementation of a btree_walker for SDB

**Comment by prakashsurya** [comment]
Here's a link to Sara's PR adding a btree walker: https://github.com/delphix/sdb/pull/71
