### ISSUE TITLE
control-c should terminate pipeline and return to sdb prompt

### ISSUE THREAD

**Issue by ahrens** [delphix/sdb#73]
Long-running command/pipeline should be interruptable without exiting sdb:

```
> long_command
...
^CTraceback (most recent call last):
  File "/usr/local/bin/sdb", line 11, in <module>
    load_entry_point('sdb==0.1.0', 'console_scripts', 'sdb')()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/cli.py", line 216, in main
    repl.start_session()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 114, in start_session
    _ = self.eval_cmd(line)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 87, in eval_cmd
    for obj in objs:
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/__init__.py", line 180, in invoke
    yield from execute_pipeline(prog, first_input, pipeline)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/__init__.py", line 77, in execute_pipeline
    yield from pipeline[-1].call(this_input)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/locator.py", line 119, in call
    self.pretty_print(self.caller(objs))
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/commands/zfs/dbuf.py", line 103, in pretty_print
    for dbuf in dbufs:
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/locator.py", line 111, in caller
    yield from self.no_input()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/commands/zfs/dbuf.py", line 141, in no_input
    while dbuf:
KeyboardInterrupt
```

**Comment by prakashsurya** [comment]
Similarly, ctrl-c should return a new prompt, even when not running any command.

For example, in bash:
```
$ cat /etc/passwd | grep user | wc -l ^C
$ 
```

But in SDB, this will exit the session:
```
> spa | head 1 | type ^C
$ 
```
