### ISSUE TITLE
member: crash when attempting to dereference invalid memory from casted bogus pointer

### ISSUE THREAD

**Issue by sdimitro** [delphix/sdb#8]
```
> echo 0x0 | cast spa_t *
(spa_t *)0x0
> echo 0x0 | cast spa_t * | member spa_name
Traceback (most recent call last):
  File "/usr/local/bin/sdb", line 11, in <module>
    load_entry_point('sdb==0.1.0', 'console_scripts', 'sdb')()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/cli.py", line 216, in main
    repl.start_session()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 114, in start_session
    _ = self.eval_cmd(line)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 88, in eval_cmd
    print(obj)
_drgn.FaultError: could not find memory segment containing 0x0```

**Comment by sdimitro** [comment]
This will be fixed once PR #17 makes it in. Doing the same with that patch outputs the following:
```
> echo 0x0 | cast spa_t * | member spa_name
warning: member: cannot dereference NULL member of type 'spa_t *'
```
