### ISSUE TITLE
Piping a command to `less` and quiting sometimes crashes SDB

### ISSUE THREAD

**Issue by sdimitro** [delphix/sdb#9]
```
> spl_kmem_caches | filter obj.skc_linux_cache > 0x0 ! less
Traceback (most recent call last):
  File "/usr/local/bin/sdb", line 11, in <module>
    load_entry_point('sdb==0.1.0', 'console_scripts', 'sdb')()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/cli.py", line 216, in main
    repl.start_session()
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 114, in start_session
    _ = self.eval_cmd(line)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 88, in eval_cmd
    print(obj)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name=6 encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by sdimitro** [comment]
Changed the title above because the following worked normally for this example:
```> stacks ! less
>```

**Comment by ahrens** [comment]
It's tricky to reproduce this because you need enough output that `less` doesn't read it all in one go.  `spa | echo ! less` and then quitting less reproduces it on my system, with 2 pools:

```
sdb> spa | echo !wc
   6236   16940  160144
sdb> spa | echo !less
sdb encountered an internal error due to a bug. Here's the
information you need to file the bug:
----------------------------------------------------------
Target Info:
	ProgramFlags.IS_LIVE|IS_LINUX_KERNEL
	Platform(<Architecture.X86_64: 1>, <PlatformFlags.IS_LITTLE_ENDIAN|IS_64_BIT: 3>)

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 86, in eval_cmd
    print(obj)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------------------------
Link: https://github.com/delphix/sdb/issues/new
```
